### ISSUE TITLE
点击展开按钮不展开，正式网站没问题

### ISSUE THREAD

**Issue by scarqin** [docschina/developer.chrome.com#11]
![](https://user-images.githubusercontent.com/15225835/187717344-a25dd0fc-4e78-48d1-8441-b0d0a17d6a37.png)
https://developer.chrome.com/docs/extensions/mv3/
@QC-L

**Comment by Otto-J** [comment]
经过努力，现在解决了

**Comment by scarqin** [comment]
@Otto-J 什么原因，我当时尝试解决失败了

**Comment by Otto-J** [comment]
问题在于访问页面时候 js 资源加载失败，控制台一堆404的资源，负责折叠的逻辑没有加载。把 404 的资源映射对就行。

原因是 dist目录有多个文件夹，比如
- dist/js 
- dist/en

我们部署时候默认入口 dist/en ，这样能打开页面，但是 Js 还在 dist/js 下，访问会失败，造成资源 404。

我改动一个部署命令，执行部署时候，把  /distjs 移动到 dist/en/js 下。
