### ISSUE TITLE
Chrome Extensions 的翻译工作可以开始了！欢迎来认领翻译、校对

### ISSUE THREAD

**Issue by Otto-J** [docschina/developer.chrome.com#2]
Chrome Extensions 目前推出了 v3 版本，欢迎大家一起来参与翻译、校对

![image](https://user-images.githubusercontent.com/9958583/159439169-cb3fb3bb-603c-4d5d-85e0-c474ba4b4dee.png)

流程：
- 先翻译再校对，先认领再翻译
- 为了避免重复翻译，多个重复翻译以第一个为主
- 如果精力有限可以在 issues 里发通知，及时调整

想到了再补充，那让我们正式开始吧！😄

**Comment by scarqin** [comment]
mark
